//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSendTest.EmailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmartEmail", Namespace="http://email.webservice.web-zy.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmailSendTest.EmailService.ReceivedMail))]
    public partial class SmartEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailSeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCAddress {
            get {
                return this.CCAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CCAddressField, value) != true)) {
                    this.CCAddressField = value;
                    this.RaisePropertyChanged("CCAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFormat {
            get {
                return this.EmailFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailFormatField, value) != true)) {
                    this.EmailFormatField = value;
                    this.RaisePropertyChanged("EmailFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailSeverity {
            get {
                return this.EmailSeverityField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailSeverityField, value) != true)) {
                    this.EmailSeverityField = value;
                    this.RaisePropertyChanged("EmailSeverity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverAddress {
            get {
                return this.ReceiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAddressField, value) != true)) {
                    this.ReceiverAddressField = value;
                    this.RaisePropertyChanged("ReceiverAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverName {
            get {
                return this.ReceiverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNameField, value) != true)) {
                    this.ReceiverNameField = value;
                    this.RaisePropertyChanged("ReceiverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderAddress {
            get {
                return this.SenderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderAddressField, value) != true)) {
                    this.SenderAddressField = value;
                    this.RaisePropertyChanged("SenderAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName {
            get {
                return this.SenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNameField, value) != true)) {
                    this.SenderNameField = value;
                    this.RaisePropertyChanged("SenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceivedMail", Namespace="http://email.webservice.web-zy.com")]
    [System.SerializableAttribute()]
    public partial class ReceivedMail : EmailSendTest.EmailService.SmartEmail {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachedFileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EmailSentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachedFileId {
            get {
                return this.AttachedFileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedFileIdField, value) != true)) {
                    this.AttachedFileIdField = value;
                    this.RaisePropertyChanged("AttachedFileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EmailSentTime {
            get {
                return this.EmailSentTimeField;
            }
            set {
                if ((this.EmailSentTimeField.Equals(value) != true)) {
                    this.EmailSentTimeField = value;
                    this.RaisePropertyChanged("EmailSentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://email.webservice.web-zy.com", ConfigurationName="EmailService.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/SendEmail", ReplyAction="http://email.webservice.web-zy.com/IEmailService/SendEmailResponse")]
        bool SendEmail(EmailSendTest.EmailService.SmartEmail Email, string IdentityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/ReceivedEmail", ReplyAction="http://email.webservice.web-zy.com/IEmailService/ReceivedEmailResponse")]
        void ReceivedEmail(string IdentityId, string StartUID, string EndUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/ReadEmail", ReplyAction="http://email.webservice.web-zy.com/IEmailService/ReadEmailResponse")]
        void ReadEmail(string IdentityId, string UID, bool Readed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/RetrievedEmail", ReplyAction="http://email.webservice.web-zy.com/IEmailService/RetrievedEmailResponse")]
        EmailSendTest.EmailService.ReceivedMail[] RetrievedEmail(string IdentityId, string StartUID, string EndUID, double size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/RetrievedAttchement", ReplyAction="http://email.webservice.web-zy.com/IEmailService/RetrievedAttchementResponse")]
        string RetrievedAttchement(string IdentityId, int AttcheFileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/checkFirstUnReadUID", ReplyAction="http://email.webservice.web-zy.com/IEmailService/checkFirstUnReadUIDResponse")]
        string checkFirstUnReadUID(string IdentityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://email.webservice.web-zy.com/IEmailService/checkLastUID", ReplyAction="http://email.webservice.web-zy.com/IEmailService/checkLastUIDResponse")]
        string checkLastUID(string IdentityId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : EmailSendTest.EmailService.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<EmailSendTest.EmailService.IEmailService>, EmailSendTest.EmailService.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendEmail(EmailSendTest.EmailService.SmartEmail Email, string IdentityId) {
            return base.Channel.SendEmail(Email, IdentityId);
        }
        
        public void ReceivedEmail(string IdentityId, string StartUID, string EndUID) {
            base.Channel.ReceivedEmail(IdentityId, StartUID, EndUID);
        }
        
        public void ReadEmail(string IdentityId, string UID, bool Readed) {
            base.Channel.ReadEmail(IdentityId, UID, Readed);
        }
        
        public EmailSendTest.EmailService.ReceivedMail[] RetrievedEmail(string IdentityId, string StartUID, string EndUID, double size) {
            return base.Channel.RetrievedEmail(IdentityId, StartUID, EndUID, size);
        }
        
        public string RetrievedAttchement(string IdentityId, int AttcheFileId) {
            return base.Channel.RetrievedAttchement(IdentityId, AttcheFileId);
        }
        
        public string checkFirstUnReadUID(string IdentityId) {
            return base.Channel.checkFirstUnReadUID(IdentityId);
        }
        
        public string checkLastUID(string IdentityId) {
            return base.Channel.checkLastUID(IdentityId);
        }
    }
}
