//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.EmailService.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int Id { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverAddress { get; set; }
        public string CCAddress { get; set; }
        public string Subject { get; set; }
        public string EmailContent { get; set; }
        public string EmailFormat { get; set; }
        public string EmailSeverity { get; set; }
        public bool EmailSent { get; set; }
        public string Remarks { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
