//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.EmailService.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedEmail
    {
        public ReceivedEmail()
        {
            this.AttachmentFiles = new HashSet<AttachmentFile>();
        }
    
        public int Id { get; set; }
        public string UID { get; set; }
        public System.DateTime EmailSentTime { get; set; }
        public int EmailAccountFk { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public string Subject { get; set; }
        public string EmailContent { get; set; }
        public string EmailFormat { get; set; }
        public string EmailSeverity { get; set; }
        public bool AttachedFile { get; set; }
        public bool Readed { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Setting Setting { get; set; }
        public virtual ICollection<AttachmentFile> AttachmentFiles { get; set; }
    }
}
