//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.EmailService.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Setting()
        {
            this.ReceivedEmails = new HashSet<ReceivedEmail>();
            this.ServiceAccounts = new HashSet<ServiceAccount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SMTP { get; set; }
        public string POP3 { get; set; }
        public string IMAP { get; set; }
        public bool SaveToServer { get; set; }
        public Nullable<int> POPPort { get; set; }
        public Nullable<bool> POPsecurity { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<bool> SMTPsecurity { get; set; }
        public Nullable<int> IMAPPort { get; set; }
        public Nullable<bool> IMAPsecurity { get; set; }
        public string EmailAddress { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> DefaultServer { get; set; }
        public Nullable<int> TimerCycle { get; set; }
        public string Remarks { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<ReceivedEmail> ReceivedEmails { get; set; }
        public virtual ICollection<ServiceAccount> ServiceAccounts { get; set; }
    }
}
