//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webzy.EmailService.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webzyEmailEntities : DbContext
    {
        public webzyEmailEntities()
            : base("name=webzyEmailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmailLog> EmailLogs { get; set; }
        public DbSet<ReceivedEmail> ReceivedEmails { get; set; }
        public DbSet<ServiceAccount> ServiceAccounts { get; set; }
        public DbSet<ServiceLog> ServiceLogs { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<EmailReceivedView> EmailReceivedViews { get; set; }
        public DbSet<AttachmentFile> AttachmentFiles { get; set; }
    }
}
